apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pippo
  name: pippo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pippo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pippo
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
