apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pippo-alpine
  name: pippo-alpine
  #namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pippo-alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pippo-alpine
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}
